baseURL = "https://jayward.org/"

[markup.highlight]
    style = "github-dark"

[params]
    author = "Jay Ward"
    info = "Tech Wizardry"
    
    enableTwemodi = true


[module]
[module.hugoVersion]
min = "0.77.0"